version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 17
.initialize

    { prep_z q[0] | prep_z q[1] | prep_z q[2] | prep_z q[3] | prep_z q[4] | prep_z q[5] | prep_z q[6] | prep_z q[7] | prep_z q[8] }
    wait 1
    { prep_z q[9] | prep_z q[10] | prep_z q[11] | prep_z q[12] | prep_z q[13] | prep_z q[14] | prep_z q[15] | prep_z q[16] | h q[0] | h q[1] | h q[2] | h q[3] | h q[4] | h q[5] | h q[6] | h q[7] | h q[8] }
    wait 1
    display

.surface_code_cycle

    { h q[9] | h q[11] }
    wait 1
    { cnot q[9],q[1] | cnot q[11],q[0] }
    wait 3
    cnot q[11],q[1]
    wait 3
    cnot q[11],q[3]
    wait 1
    { h q[12] | h q[10] }
    wait 1
    { cnot q[9],q[2] | cnot q[11],q[4] | cz q[12],q[0] | cz q[10],q[1] }
    wait 1
    h q[14]
    wait 1
    { cnot q[14],q[4] | cz q[12],q[3] | cz q[10],q[2] }
    wait 1
    h q[13]
    wait 1
    { cnot q[14],q[5] | cz q[10],q[4] | cz q[13],q[3] }
    wait 1
    h q[16]
    wait 1
    { cnot q[14],q[7] | cnot q[16],q[6] | cz q[10],q[5] | cz q[13],q[4] }
    wait 1
    h q[15]
    wait 1
    { cnot q[14],q[8] | cnot q[16],q[7] | cz q[13],q[6] | cz q[15],q[5] }
    wait 3
    { cz q[13],q[7] | cz q[15],q[8] }
    wait 3
    { h q[9] | h q[11] | h q[14] | h q[16] | h q[12] | h q[10] | h q[13] | h q[15] }
    wait 1
    display

.syndromes_code

    { measure q[9] | measure q[11] | measure q[14] | measure q[16] | measure q[12] | measure q[10] | measure q[13] | measure q[15] }
    wait 14
    display

