version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 9
.initialize

    prep_z q[0]
    wait 1
    rx q[0], 1.3
    wait 1
    { prep_z q[1] | prep_z q[2] | prep_z q[3] | prep_z q[4] | prep_z q[5] | prep_z q[6] | prep_z q[7] | prep_z q[8] | ry q[0], 0.3 }
    wait 1
    display

.phase_encode

    cnot q[0],q[3]
    wait 3
    cnot q[0],q[6]
    wait 3
    { h q[0] | h q[3] | h q[6] }
    wait 1
    display

.bitflip_encode

    { cnot q[0],q[1] | cnot q[3],q[4] | cnot q[6],q[7] }
    wait 3
    { cnot q[0],q[2] | cnot q[3],q[5] | cnot q[6],q[8] }
    wait 3
    display

.inject_error

    x q[0]
    wait 1
    { z q[0] | x q[1] }
    wait 1
    display

.bitflip_decode_and_correct

    { cnot q[0],q[1] | cnot q[3],q[4] | cnot q[6],q[7] }
    wait 3
    { cnot q[0],q[2] | cnot q[3],q[5] | cnot q[6],q[8] }
    wait 3
    { toffoli q[2],q[1],q[0] | toffoli q[5],q[4],q[3] | toffoli q[8],q[7],q[6] }
    wait 3
    display

.phaseflip_decode_and_correct

    { h q[0] | h q[3] }
    wait 1
    cnot q[0],q[3]
    wait 1
    h q[6]
    wait 1
    cnot q[0],q[6]
    wait 3
    toffoli q[6],q[3],q[0]
    wait 3
    display

