version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 3

.initialize
    prep_z q[0]
    prep_z q[1]
    prep_z q[2]
    h q[0]
    h q[1]
    h q[2]
    display

.oracle
    x q[2]
    h q[2]
    toffoli q[0],q[1],q[2]
    h q[2]
    x q[2]
    display

.amplify
    h q[0]
    h q[1]
    h q[2]
    x q[0]
    x q[1]
    x q[2]
    h q[2]
    toffoli q[0],q[1],q[2]
    h q[2]
    x q[0]
    x q[1]
    x q[2]
    h q[0]
    h q[1]
    h q[2]
    display
