version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 3
.initialize

    prep_z q[0]
    wait 1
    { prep_z q[1] | prep_z q[2] | x q[0] }
    wait 1
    display

.entangle

    h q[1]
    wait 1
    cnot q[1],q[2]
    wait 3
    display

.teleport

    cnot q[0],q[1]
    wait 3
    h q[0]
    wait 1
    display

