version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 3

.kernel_1
    prep_z q[0]
    prep_z q[1]
    prep_z q[2]
    x q[0]
    y q[1]
    z q[2]
    h q[0]
    h q[0]
    i q[0]
    i q[0]
    s q[0]
    sdag q[0]
    t q[0]
    tdag q[0]
    rx q[0], 0.15
    ry q[0], 0.15
    rz q[0], 0.15
    swap q[0],q[1]
    cz q[0],q[1]
    cnot q[0],q[1]
    toffoli q[0],q[1],q[1]
    display

.kernel_2
    measure q[0]
    measure q[1]
    measure q[2]
    display
