version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 3

.initialize
    prep_z q[0]
    prep_z q[1]
    prep_z q[2]
    x q[0]
    display

.entangle
    h q[1]
    cnot q[1],q[2]
    display

.teleport
    cnot q[0],q[1]
    h q[0]
    display

.decode
    measure q[0]
    measure q[1]
    cnot q[1],q[2]
    cz q[0],q[2]
    display
