version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 3
.kernel_1

    prep_z q[0]
    wait 1
    x q[0]
    wait 1
    h q[0]
    wait 1
    h q[0]
    wait 1
    i q[0]
    wait 1
    i q[0]
    wait 1
    s q[0]
    wait 1
    sdag q[0]
    wait 1
    t q[0]
    wait 1
    tdag q[0]
    wait 1
    rx q[0], 0.15
    wait 1
    { prep_z q[1] | ry q[0], 0.15 }
    wait 1
    { y q[1] | rz q[0], 0.15 }
    wait 1
    swap q[0],q[1]
    wait 3
    cz q[0],q[1]
    wait 3
    cz q[0],q[1]
    wait 3
    cnot q[0],q[1]
    wait 3
    toffoli q[0],q[1],q[1]
    wait 1073741694
    prep_z q[2]
    wait 1
    z q[2]
    wait 1
    display

.kernel_2

    { measure q[0] | measure q[1] | measure q[2] }
    wait 14
    display

